In [92]:
import numpy as np
import pandas as pd
from biopandas.pdb import PandasPdb

In [93]:
ppdb = PandasPdb().read_pdb('4ydl.pdb')
atom_df = ppdb.df['ATOM'].copy(deep=True)
atom_df.head()

,record_name,atom_number,blank_1,atom_name,alt_loc,residue_name,blank_2,chain_id,residue_number,insertion,...,x_coord,y_coord,z_coord,occupancy,b_factor,blank_4,segment_id,element_symbol,charge,line_idx
0,ATOM,1,,N,,VAL,,G,44,,...,-40.184,69.736,-48.615,1.0,92.10,,,N,NaN,5
1,ATOM,2,,CA,,VAL,,G,44,,...,-39.749,70.530,-49.757,1.0,87.67,,,C,NaN,6
2,ATOM,3,,C,,VAL,,G,44,,...,-38.516,69.888,-50.392,1.0,83.22,,,C,NaN,7
3,ATOM,4,,O,,VAL,,G,44,,...,-37.727,69.228,-49.712,1.0,84.92,,,O,NaN,8
4,ATOM,5,,CB,,VAL,,G,44,,...,-39.448,71.996,-49.341,1.0,88.67,,,C,NaN,9

In [94]:
Heavy_chain = atom_df[atom_df['chain_id'] == 'B'] ## Heavy chain
# Heavy_chain.drop_duplicates(['chain_id','residue_number'])
Heavy_chain

,record_name,atom_number,blank_1,atom_name,alt_loc,residue_name,blank_2,chain_id,residue_number,insertion,...,x_coord,y_coord,z_coord,occupancy,b_factor,blank_4,segment_id,element_symbol,charge,line_idx
8704,ATOM,9945,,N,,VAL,,B,2,,...,-23.700,15.707,-43.752,1.0,34.70,,,N,NaN,9949
8705,ATOM,9946,,CA,,VAL,,B,2,,...,-23.190,16.399,-44.923,1.0,35.56,,,C,NaN,9950
8706,ATOM,9947,,C,,VAL,,B,2,,...,-23.807,15.785,-46.179,1.0,38.16,,,C,NaN,9951
8707,ATOM,9948,,O,,VAL,,B,2,,...,-23.797,14.566,-46.365,1.0,41.43,,,O,NaN,9952
8708,ATOM,9949,,CB,,VAL,,B,2,,...,-21.654,16.336,-44.977,1.0,41.40,,,C,NaN,9953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10393,ATOM,11634,,CA,,CYS,,B,216,,...,-40.317,-21.355,-92.076,1.0,75.18,,,C,NaN,11638
10394,ATOM,11635,,C,,CYS,,B,216,,...,-40.323,-20.707,-93.460,1.0,75.41,,,C,NaN,11639
10395,ATOM,11636,,O,,CYS,,B,216,,...,-41.175,-21.008,-94.295,1.0,76.59,,,O,NaN,11640
10396,ATOM,11637,,CB,,CYS,,B,216,,...,-40.798,-22.807,-92.182,1.0,80.88,,,C,NaN,11641
10397,ATOM,11638,,SG,,CYS,,B,216,,...,-39.956,-23.967,-91.076,1.0,165.37,,,S,NaN,11642

In [95]:
Light_chain = atom_df[atom_df['chain_id'] == 'C'] ## Light chain
# Light_chain.drop_duplicates(['chain_id','residue_number']).head()
Light_chain

,record_name,atom_number,blank_1,atom_name,alt_loc,residue_name,blank_2,chain_id,residue_number,insertion,...,x_coord,y_coord,z_coord,occupancy,b_factor,blank_4,segment_id,element_symbol,charge,line_idx
10398,ATOM,11902,,N,,GLU,,C,1,,...,4.705,15.307,-58.335,1.0,77.86,,,N,NaN,11906
10399,ATOM,11903,,CA,,GLU,,C,1,,...,3.416,14.711,-58.006,1.0,72.62,,,C,NaN,11907
10400,ATOM,11904,,C,,GLU,,C,1,,...,3.587,13.407,-57.237,1.0,69.31,,,C,NaN,11908
10401,ATOM,11905,,O,,GLU,,C,1,,...,4.687,12.857,-57.151,1.0,72.63,,,O,NaN,11909
10402,ATOM,11906,,CB,,GLU,,C,1,,...,2.597,14.451,-59.269,1.0,74.44,,,C,NaN,11910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12029,ATOM,13533,,CA,,CYS,,C,214,,...,-35.504,-22.259,-91.773,1.0,103.54,,,C,NaN,13537
12030,ATOM,13534,,C,,CYS,,C,214,,...,-34.968,-22.954,-90.518,1.0,104.54,,,C,NaN,13538
12031,ATOM,13535,,O,,CYS,,C,214,,...,-33.869,-23.514,-90.519,1.0,104.60,,,O,NaN,13539
12032,ATOM,13536,,CB,,CYS,,C,214,,...,-36.724,-23.016,-92.306,1.0,107.64,,,C,NaN,13540
12033,ATOM,13537,,SG,,CYS,,C,214,,...,-38.067,-23.217,-91.105,1.0,194.72,,,S,NaN,13541

In [96]:
Antigen_chain = atom_df[atom_df['chain_id'] == 'A'] ## Antigen chain
Antigen_chain

,record_name,atom_number,blank_1,atom_name,alt_loc,residue_name,blank_2,chain_id,residue_number,insertion,...,x_coord,y_coord,z_coord,occupancy,b_factor,blank_4,segment_id,element_symbol,charge,line_idx
2689,ATOM,3051,,N,,VAL,,A,44,,...,7.375,23.552,-14.838,1.0,76.65,,,N,NaN,3055
2690,ATOM,3052,,CA,,VAL,,A,44,,...,6.699,22.582,-15.690,1.0,72.92,,,C,NaN,3056
2691,ATOM,3053,,C,,VAL,,A,44,,...,5.459,23.206,-16.319,1.0,72.54,,,C,NaN,3057
2692,ATOM,3054,,O,,VAL,,A,44,,...,4.615,23.774,-15.622,1.0,73.28,,,O,NaN,3058
2693,ATOM,3055,,CB,,VAL,,A,44,,...,6.299,21.315,-14.901,1.0,76.12,,,C,NaN,3059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5369,ATOM,5731,,CB,,GLU,,A,492,,...,1.895,22.012,-14.032,1.0,97.34,,,C,NaN,5735
5370,ATOM,5732,,CG,,GLU,,A,492,,...,1.315,21.641,-15.383,1.0,97.21,,,C,NaN,5736
5371,ATOM,5733,,CD,,GLU,,A,492,,...,1.656,20.226,-15.794,1.0,100.25,,,C,NaN,5737
5372,ATOM,5734,,OE1,,GLU,,A,492,,...,2.310,19.517,-14.999,1.0,105.04,,,O,NaN,5738
5373,ATOM,5735,,OE2,,GLU,,A,492,,...,1.270,19.825,-16.911,1.0,98.66,,,O,NaN,5739

In [97]:
A_coord = Antigen_chain[['x_coord','y_coord','z_coord']].to_numpy()
H_coord = Heavy_chain[['x_coord','y_coord','z_coord']].to_numpy()
L_coord = Light_chain[['x_coord','y_coord','z_coord']].to_numpy()

In [43]:
## Looping every residue from heavy chain overy every residue from antigen chain to calculate distance 

distance = []
for a in range(len(A_coord)):
    dep=[]
    for h in range(len(H_coord)):
        dist = np.sqrt(int(A_coord[a][0]-H_coord[h][0])^2 +
                       int(A_coord[a][1]-H_coord[h][1])^2+
                       int(A_coord[a][2]-H_coord[h][2])^2)
        dep.append(dist)
    distance.append(dep)

/Users/apawar/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in sqrt
  if __name__ == '__main__':

In [49]:
dist_matrix = np.array(distance)
dist_matrix.shape

(2685, 1694)

In [85]:
row_names = 'Antigen_' + Antigen_chain['residue_name'].to_numpy()
column_names = 'H_' + Heavy_chain['residue_name'].to_numpy()

In [86]:
df_heavy = pd.DataFrame(dist_matrix, columns=column_names, index=row_names)

In [87]:
df_heavy

,H_VAL,H_VAL,H_VAL,H_VAL,H_VAL,H_VAL,H_VAL,H_ARG,H_ARG,H_ARG,...,H_SER,H_SER,H_SER,H_SER,H_CYS,H_CYS,H_CYS,H_CYS,H_CYS,H_CYS
Antigen_VAL,3.162278,7.280110,7.280110,7.348469,7.348469,7.416198,2.828427,7.416198,2.828427,3.741657,...,8.944272,8.888194,9.273618,9.273618,9.055385,8.717798,9.110434,8.774964,8.774964,9.055385
Antigen_VAL,3.162278,2.828427,7.211103,7.348469,3.000000,7.874008,0.000000,7.681146,7.416198,7.549834,...,8.660254,8.602325,9.219544,9.273618,8.774964,8.831761,8.888194,8.944272,8.717798,9.000000
Antigen_VAL,3.316625,2.828427,3.000000,7.280110,3.872983,3.872983,3.605551,7.416198,7.211103,7.416198,...,8.717798,8.544004,9.219544,9.055385,8.774964,8.717798,8.774964,8.774964,9.000000,9.055385
Antigen_VAL,3.162278,3.872983,7.416198,7.280110,3.741657,7.141428,3.605551,7.416198,7.211103,7.211103,...,8.888194,8.888194,8.602325,9.219544,8.717798,8.888194,8.888194,9.000000,9.000000,9.055385
Antigen_VAL,2.449490,7.549834,7.615773,7.280110,7.937254,7.874008,1.000000,7.483315,7.549834,7.874008,...,8.602325,8.660254,9.327379,9.165151,8.485281,8.888194,8.944272,8.944272,8.717798,8.774964
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Antigen_GLU,3.464102,7.745967,7.000000,6.928203,7.071068,6.928203,3.605551,7.810250,7.681146,7.681146,...,8.774964,8.831761,8.602325,8.660254,8.602325,9.219544,9.219544,9.273618,9.273618,8.660254
Antigen_GLU,1.414214,1.414214,7.745967,7.071068,3.464102,7.071068,3.464102,7.810250,7.810250,7.549834,...,8.888194,8.717798,8.602325,8.602325,8.544004,8.544004,9.327379,9.165151,8.485281,8.544004
Antigen_GLU,0.000000,0.000000,7.810250,7.745967,3.872983,7.000000,3.464102,7.745967,7.745967,7.874008,...,8.717798,8.831761,8.602325,8.185353,8.888194,8.831761,8.831761,9.110434,8.660254,8.485281
Antigen_GLU,1.732051,1.000000,7.745967,7.937254,3.872983,6.928203,3.872983,7.874008,7.937254,7.483315,...,8.717798,8.831761,8.306624,8.366600,8.774964,8.774964,9.055385,9.055385,8.602325,8.660254
Antigen_GLU,0.000000,1.000000,1.414214,1.732051,3.872983,3.872983,3.464102,7.874008,7.745967,7.810250,...,8.602325,8.888194,8.124038,8.124038,8.831761,8.774964,8.888194,8.774964,8.544004,8.602325

### Light Chain distance

In [88]:
## Looping every residue from heavy chain overy every residue from antigen chain to calculate distance 

distance_L = []
for a in range(len(A_coord)):
    dep=[]
    for h in range(len(L_coord)):
        dist = np.sqrt(int(A_coord[a][0]-L_coord[h][0])^2 +
                       int(A_coord[a][1]-L_coord[h][1])^2+
                       int(A_coord[a][2]-L_coord[h][2])^2)
        dep.append(dist)
    distance_L.append(dep)

/Users/apawar/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in sqrt
  if __name__ == '__main__':

In [89]:
L_dist_matrix = np.array(distance_L)
L_dist_matrix.shape

(2685, 1636)

In [90]:
row_names = 'Antigen_' + Antigen_chain['residue_name'].to_numpy()
column_names = 'L_' + Light_chain['residue_name'].to_numpy()
df_light = pd.DataFrame(L_dist_matrix, columns=column_names, index=row_names)

In [91]:
df_light

,L_GLU,L_GLU,L_GLU,L_GLU,L_GLU,L_GLU,L_GLU,L_GLU,L_GLU,L_ILE,...,L_GLU,L_GLU,L_GLU,L_GLU,L_CYS,L_CYS,L_CYS,L_CYS,L_CYS,L_CYS
Antigen_VAL,6.244998,6.164414,5.744563,5.656854,5.916080,6.082763,7.681146,7.681146,6.164414,5.744563,...,8.306624,8.366600,8.246211,9.380832,8.660254,8.544004,9.219544,9.327379,9.000000,9.000000
Antigen_VAL,6.164414,6.000000,5.744563,5.656854,5.744563,6.000000,6.082763,7.615773,6.082763,6.244998,...,9.539392,9.433981,8.426150,9.380832,8.602325,8.485281,8.485281,9.273618,8.485281,8.717798
Antigen_VAL,6.244998,5.744563,5.830952,6.000000,6.164414,6.164414,5.916080,5.830952,6.164414,6.164414,...,9.433981,9.746794,8.185353,9.643651,8.246211,8.485281,9.273618,9.433981,9.219544,9.219544
Antigen_VAL,6.000000,6.000000,6.000000,6.082763,6.164414,5.744563,5.830952,7.810250,5.830952,6.244998,...,9.380832,9.643651,8.124038,9.591663,8.306624,9.165151,9.433981,9.433981,9.219544,9.219544
Antigen_VAL,6.164414,6.082763,6.082763,6.082763,6.244998,6.244998,5.916080,7.810250,5.916080,5.656854,...,9.433981,9.433981,8.426150,8.062258,8.485281,8.485281,8.485281,8.544004,8.485281,8.831761
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Antigen_GLU,NaN,NaN,NaN,NaN,6.000000,NaN,7.549834,7.681146,7.549834,6.082763,...,9.643651,8.185353,11.224972,11.180340,9.380832,8.366600,8.366600,8.000000,9.539392,8.306624
Antigen_GLU,NaN,NaN,NaN,NaN,NaN,NaN,6.164414,7.549834,6.244998,NaN,...,9.643651,9.899495,11.180340,9.899495,8.185353,8.306624,8.306624,8.185353,8.246211,8.366600
Antigen_GLU,NaN,NaN,NaN,NaN,6.324555,NaN,6.000000,7.681146,6.164414,5.744563,...,8.062258,11.135529,9.899495,11.180340,8.306624,8.366600,8.426150,8.000000,8.426150,8.306624
Antigen_GLU,NaN,NaN,NaN,NaN,6.557439,6.082763,6.082763,7.681146,6.082763,5.744563,...,9.695360,9.746794,9.643651,11.269428,8.124038,8.124038,8.366600,8.366600,8.366600,8.485281
Antigen_GLU,NaN,NaN,NaN,NaN,NaN,NaN,6.164414,6.000000,6.164414,NaN,...,8.062258,11.180340,11.135529,11.269428,8.426150,8.366600,8.062258,8.426150,8.366600,8.246211